# Generated by Django 2.0.5 on 2018-06-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('photo', models.ImageField(upload_to='image/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Футболки',
                'verbose_name_plural': 'Футболки',
            },
        ),
    ]
