# Generated by Django 2.0.5 on 2018-06-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_shirt',
            name='top',
            field=models.BooleanField(default=False, verbose_name='В топ?'),
        ),
    ]
