# Generated by Django 2.0.5 on 2018-06-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt', '0002_t_shirt_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_shirt',
            name='adress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка'),
        ),
    ]
